accounts:
  - name: household0
    coins: ["100000token", "10000000stake"]
  - name: household1
    coins: ["100000token", "10000000stake"]
  - name: household2
    coins: ["100000token", "10000000stake"]
  - name: household3
    coins: ["100000token", "10000000stake"]
  - name: household4
    coins: ["100000token", "10000000stake"]
  - name: household5
    coins: ["100000token", "10000000stake"]
  - name: household6
    coins: ["100000token", "10000000stake"]
  - name: household7
    coins: ["100000token", "10000000stake"]
  - name: household8
    coins: ["100000token", "10000000stake"]
  - name: household9
    coins: ["100000token", "10000000stake"]
  - name: household10
    coins: ["100000token", "10000000stake"]
  - name: household11
    coins: ["100000token", "10000000stake"]
  - name: household12
    coins: ["100000token", "10000000stake"]
  - name: household13
    coins: ["100000token", "10000000stake"]
  - name: household14
    coins: ["100000token", "10000000stake"]
  - name: household15
    coins: ["100000token", "10000000stake"]
  - name: household16
    coins: ["100000token", "10000000stake"]
  - name: household17
    coins: ["100000token", "10000000stake"]
  - name: household18
    coins: ["100000token", "10000000stake"]
  - name: household19
    coins: ["100000token", "10000000stake"]
  - name: household20
    coins: ["100000token", "10000000stake"]
  - name: household21
    coins: ["100000token", "10000000stake"]
  - name: household22
    coins: ["100000token", "10000000stake"]
  - name: household23
    coins: ["100000token", "10000000stake"]
  - name: household24
    coins: ["100000token", "10000000stake"]
  - name: household25
    coins: ["100000token", "10000000stake"]
  - name: household26
    coins: ["100000token", "10000000stake"]
  - name: household27
    coins: ["100000token", "10000000stake"]
  - name: household28
    coins: ["100000token", "10000000stake"]
  - name: household29
    coins: ["100000token", "10000000stake"]
validator:
  name: household0
  staked: "10000000stake"
  name: household1
  staked: "10000000stake"
  name: household2
  staked: "10000000stake"
  name: household3
  staked: "10000000stake"
  name: household4
  staked: "10000000stake"
  name: household5
  staked: "10000000stake"
  name: household6
  staked: "10000000stake"
  name: household7
  staked: "10000000stake"
  name: household8
  staked: "10000000stake"
  name: household9
  staked: "10000000stake"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: household1
  coins: ["5token", "100000stake"]
