accounts:
  - name: household0
    coins: ["10000token", "100000000stake"]
  - name: household1
    coins: ["10000token", "100000000stake"]
  - name: household2
    coins: ["10000token", "100000000stake"]
  - name: household3
    coins: ["10000token", "100000000stake"]
  - name: household4
    coins: ["10000token", "100000000stake"]
  - name: household5
    coins: ["10000token", "100000000stake"]
  - name: household6
    coins: ["10000token", "100000000stake"]
  - name: household7
    coins: ["10000token", "100000000stake"]
  - name: household8
    coins: ["10000token", "100000000stake"]
  - name: household9
    coins: ["10000token", "100000000stake"]
  - name: household10
    coins: ["10000token", "100000000stake"]
  - name: household11
    coins: ["10000token", "100000000stake"]
  - name: household12
    coins: ["10000token", "100000000stake"]
  - name: household13
    coins: ["10000token", "100000000stake"]
  - name: household14
    coins: ["10000token", "100000000stake"]
  - name: household15
    coins: ["10000token", "100000000stake"]
  - name: household16
    coins: ["10000token", "100000000stake"]
  - name: household17
    coins: ["10000token", "100000000stake"]
  - name: household18
    coins: ["10000token", "100000000stake"]
  - name: household19
    coins: ["10000token", "100000000stake"]
  - name: household20
    coins: ["10000token", "100000000stake"]
  - name: household21
    coins: ["10000token", "100000000stake"]
  - name: household22
    coins: ["10000token", "100000000stake"]
  - name: household23
    coins: ["10000token", "100000000stake"]
  - name: household24
    coins: ["10000token", "100000000stake"]
  - name: household25
    coins: ["10000token", "100000000stake"]
  - name: household26
    coins: ["10000token", "100000000stake"]
  - name: household27
    coins: ["10000token", "100000000stake"]
  - name: household28
    coins: ["10000token", "100000000stake"]
  - name: household29
    coins: ["10000token", "100000000stake"]
  - name: household30
    coins: ["10000token", "100000000stake"]
  - name: household31
    coins: ["10000token", "100000000stake"]
  - name: household32
    coins: ["10000token", "100000000stake"]
  - name: household33
    coins: ["10000token", "100000000stake"]
  - name: household34
    coins: ["10000token", "100000000stake"]
  - name: household35
    coins: ["10000token", "100000000stake"]
  - name: household36
    coins: ["10000token", "100000000stake"]
  - name: household37
    coins: ["10000token", "100000000stake"]
  - name: household38
    coins: ["10000token", "100000000stake"]
  - name: household39
    coins: ["10000token", "100000000stake"]
  - name: household40
    coins: ["10000token", "100000000stake"]
  - name: household41
    coins: ["10000token", "100000000stake"]
  - name: household42
    coins: ["10000token", "100000000stake"]
  - name: household43
    coins: ["10000token", "100000000stake"]
  - name: household44
    coins: ["10000token", "100000000stake"]
  - name: household45
    coins: ["10000token", "100000000stake"]
  - name: household46
    coins: ["10000token", "100000000stake"]
  - name: household47
    coins: ["10000token", "100000000stake"]
  - name: household48
    coins: ["10000token", "100000000stake"]
  - name: household49
    coins: ["10000token", "100000000stake"]
validator:
  name: household0
  staked: "100000000stake"
  name: household1
  staked: "100000000stake"
  name: household2
  staked: "100000000stake"
  name: household3
  staked: "100000000stake"
  name: household4
  staked: "100000000stake"
  name: household5
  staked: "100000000stake"
  name: household6
  staked: "100000000stake"
  name: household7
  staked: "100000000stake"
  name: household8
  staked: "100000000stake"
  name: household9
  staked: "100000000stake"
  name: household10
  staked: "100000000stake"
  name: household11
  staked: "100000000stake"
  name: household12
  staked: "100000000stake"
  name: household13
  staked: "100000000stake"
  name: household14
  staked: "100000000stake"
  name: household15
  staked: "100000000stake"
  name: household16
  staked: "100000000stake"
  name: household17
  staked: "100000000stake"
  name: household18
  staked: "100000000stake"
  name: household19
  staked: "100000000stake"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: household1
  coins: ["5token", "100000stake"]
